name: pulse_flutter
description: A Flutter app for discovering location-based deals and offers.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #  UI & Material Design
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  cloud_functions: ^6.0.6
  firebase_storage: ^13.0.6
  firebase_analytics: ^12.1.1
  

  # Google Services
  google_sign_in: ^7.2.0
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Stripe Payments
  flutter_stripe: ^12.1.1

  #QR code
  qr_flutter: ^4.1.0
  
  # Image Loading & Caching
  cached_network_image: ^3.3.0
  
  # Date & Time
  intl: ^0.20.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # UI Enhancements
  shimmer: ^3.0.0
  lottie: ^3.3.2
  
  # Utils
  uuid: ^4.2.1
  url_launcher: ^6.2.2

  # Facebook Ad integration
  facebook_app_events: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher-web.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  
  # Uncomment and add custom fonts when needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700